# Generated by Django 5.0.4 on 2024-05-29 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PERFIL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PR_CCODIGO', models.CharField(max_length=128, verbose_name='Codigo perfil')),
                ('PR_CNOMBRE', models.CharField(max_length=128, verbose_name='Nombre perfil')),
                ('PR_CDESCRIPCION', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
                ('PR_BHABILITADO', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('US_NID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Id usuario')),
            ],
            options={
                'db_table': 'PERFIL',
            },
        ),
        migrations.CreateModel(
            name='VISTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VI_CCODIGO', models.CharField(max_length=128, verbose_name='Codigo vista')),
                ('VI_CNOMBRE', models.CharField(max_length=128, verbose_name='Nombre vista')),
                ('VI_CDESCRIPCION', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
                ('VI_BHABILITADO', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('US_NID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Id usuario')),
            ],
            options={
                'db_table': 'VISTA',
            },
        ),
        migrations.CreateModel(
            name='PERMISO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PE_BHABILITADO', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('PR_NID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.perfil', verbose_name='Id perfil')),
                ('US_NID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Id usuario')),
                ('VI_NID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.vista', verbose_name='Id vista')),
            ],
            options={
                'db_table': 'PERMISO',
            },
        ),
    ]
