# Generated by Django 3.2.6 on 2024-05-29 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='USERS_EMPRESA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EP_NID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.empresa', verbose_name='Id empresa')),
                ('US_NID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Id_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'USERS_EMPRESA',
                'unique_together': {('US_NID', 'EP_NID')},
            },
        ),
    ]
