# Generated by Django 5.0.4 on 2024-05-29 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_perfil_vista_permiso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PERFIL_USUARIO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PE_BHABILITADO', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('PR_NID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.perfil', verbose_name='Id perfil')),
                ('US_NID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Id usuario')),
            ],
            options={
                'db_table': 'PERFIL_USUARIO',
            },
        ),
    ]
