# Generated by Django 3.2.6 on 2024-05-29 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_users_empresa'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='users_empresa',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='users_empresa',
            constraint=models.UniqueConstraint(fields=('US_NID',), name='unique_us_nid'),
        ),
    ]
