# Generated by Django 5.0.4 on 2024-05-29 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_citacion_ci_cmaterial'),
        ('home', '0003_perfil_usuario'),
    ]

    operations = [
    ]
