# Generated by Django 5.0.4 on 2024-05-30 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_merge_20240529_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citacion_item',
            name='CI_NCANTIDAD',
        ),
    ]
