# Generated by Django 3.2.6 on 2024-05-29 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20240529_1720'),
        ('home', '0004_merge_20240529_1748'),
    ]

    operations = [
    ]
