# Generated by Django 5.0.4 on 2024-05-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_citacion_item_ci_ncantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='citacion',
            name='CI_BHABILITADO',
            field=models.BooleanField(default=True, verbose_name='Habilitado'),
        ),
    ]
