# Generated by Django 5.0.4 on 2024-06-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_merge_20240529_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='users_extension',
            name='UX_IS_CONDUCTOR',
            field=models.BooleanField(default=False, verbose_name='Es conductor'),
        ),
    ]
