# Generated by Django 5.0.4 on 2024-06-03 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_merge_20240529_1819'),
        ('home', '0006_citacion_ci_bhabilitado'),
    ]

    operations = [
    ]
