# Generated by Django 5.0.4 on 2024-06-03 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_merge_20240603_1205'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruta',
            name='SN_NID',
        ),
        migrations.AddField(
            model_name='citacion',
            name='CI_FFECHAINICIO',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha inicio'),
        ),
        migrations.AlterField(
            model_name='citacion',
            name='CA_NID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.camion', verbose_name='Id camion'),
        ),
        migrations.AlterField(
            model_name='citacion',
            name='CON_NID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.conductor', verbose_name='id conductor'),
        ),
        migrations.AlterField(
            model_name='citacion',
            name='RUT_NID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.ruta', verbose_name='Id ruta'),
        ),
        migrations.AlterField(
            model_name='citacion',
            name='SN_NID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.socionegocio', verbose_name='Id socio negocio'),
        ),
        migrations.AlterField(
            model_name='citacion',
            name='TAR_NID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.tarifa_global', verbose_name='Id tarifa'),
        ),
        migrations.AlterField(
            model_name='citacion',
            name='US_NID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Id usuario'),
        ),
    ]
