# Generated by Django 5.0.4 on 2024-06-04 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_users_extension_ux_is_conductor'),
        ('home', '0008_remove_ruta_sn_nid_citacion_ci_ffechainicio_and_more'),
    ]

    operations = [
    ]
