# Generated by Django 5.0.4 on 2024-06-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_merge_20240604_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citacion',
            name='CI_NVALORTARIFA',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=18, null=True, verbose_name='Valor tarifa'),
        ),
    ]
