# Generated by Django 5.0.4 on 2024-06-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_citacion_ci_nvalortarifa'),
    ]

    operations = [
        migrations.AddField(
            model_name='citacion',
            name='CI_FFECHATERMINO',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha termino'),
        ),
    ]
