# Generated by Django 5.0.4 on 2024-06-05 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_citacion_ci_ffechatermino'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extra_liquidacion',
            name='CIE_NID',
        ),
        migrations.RemoveField(
            model_name='extra_liquidacion',
            name='EP_NID',
        ),
        migrations.RemoveField(
            model_name='extra_liquidacion',
            name='LI_NID',
        ),
        migrations.RemoveField(
            model_name='liquidacion',
            name='EP_NID',
        ),
        migrations.RemoveField(
            model_name='liquidacion',
            name='SN_NID',
        ),
        migrations.RemoveField(
            model_name='liquidacion',
            name='US_NID',
        ),
        migrations.DeleteModel(
            name='CITACION_LIQUIDACION',
        ),
        migrations.DeleteModel(
            name='EXTRA_LIQUIDACION',
        ),
        migrations.DeleteModel(
            name='LIQUIDACION',
        ),
    ]
