# Generated by Django 5.0.4 on 2024-06-05 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_extra_liquidacion_cie_nid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PROFORMA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRO_CESTADO', models.CharField(max_length=256, verbose_name='Estado proforma')),
                ('PRO_CCOMENTARIO', models.TextField(blank=True, null=True, verbose_name='Comentario')),
                ('PRO_NSUBTOTAL', models.DecimalField(decimal_places=5, max_digits=18, verbose_name='Sub total')),
                ('PRO_NIVA', models.DecimalField(decimal_places=5, max_digits=18, verbose_name='Iva')),
                ('PRO_NTOTAL', models.DecimalField(decimal_places=5, max_digits=18, verbose_name='Total')),
                ('PRO_NINGRESO', models.DecimalField(decimal_places=5, max_digits=18, verbose_name='Ingreso')),
                ('PRO_NDESCUENTO', models.DecimalField(decimal_places=5, max_digits=18, verbose_name='Descuento')),
                ('PRO_FFECHAREGISTRO', models.DateTimeField(blank=True, null=True, verbose_name='Fecha registro')),
                ('PRO_FFECHAEMISION', models.DateTimeField(null=True, verbose_name='Fecha emision')),
                ('EP_NID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.empresa', verbose_name='Id empresa')),
                ('US_NID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Id usuario')),
            ],
            options={
                'db_table': 'PROFORMA',
            },
        ),
        migrations.CreateModel(
            name='EXTRA_PROFORMA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EPR_NVALOR', models.DecimalField(decimal_places=5, max_digits=18, verbose_name='Valor')),
                ('CIE_NID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.citacion_extra', verbose_name='Id citacion extra')),
                ('EP_NID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.empresa', verbose_name='Id empresa')),
                ('PRO_NID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.proforma', verbose_name='Id Proforma')),
            ],
            options={
                'db_table': 'EXTRA_PROFORMA',
            },
        ),
        migrations.CreateModel(
            name='CITACION_PROFORMA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CIP_NSUBTOTAL', models.DecimalField(decimal_places=5, max_digits=18, verbose_name='Subtotal')),
                ('CI_NID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.citacion', verbose_name='id citacion')),
                ('EP_NID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.empresa', verbose_name='Id empresa')),
                ('PRO_NID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.proforma', verbose_name='Id Proforma')),
            ],
            options={
                'db_table': 'CITACION_PROFORMA',
            },
        ),
    ]
