# Generated by Django 5.0.4 on 2024-06-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_proforma_extra_proforma_citacion_proforma'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='CON_NPERIODO_EXTRA',
            field=models.IntegerField(default=0, verbose_name='Periodo extra'),
        ),
    ]
