# Generated by Django 5.0.4 on 2024-06-06 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_conductor_con_nperiodo_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='proforma',
            name='SN_NID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.socionegocio', verbose_name='Id socionegocio'),
        ),
    ]
