# Generated by Django 5.0.4 on 2024-06-09 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_proforma_sn_nid'),
    ]

    operations = [
        migrations.AddField(
            model_name='extra_proforma',
            name='EPR_BINGRESO',
            field=models.BooleanField(default=False, verbose_name='Ingreso'),
        ),
    ]
