# Generated by Django 5.0.4 on 2024-06-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_extra_proforma_epr_bingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='extra_proforma',
            name='EPR_BHABILITADO',
            field=models.BooleanField(default=True, verbose_name='Habilitado'),
        ),
    ]
