# Generated by Django 3.2.6 on 2024-06-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_extra_proforma_epr_bhabilitado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapa',
            name='ET_CTIPO',
            field=models.CharField(choices=[('OPERACION', 'Operación'), ('SALIDA', 'Salida'), ('SEGUIMIENTO', 'Seguimiento')], max_length=128, verbose_name='Tipo'),
        ),
    ]
