# Generated by Django 5.0.4 on 2024-06-10 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_extra_proforma_epr_bhabilitado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campo_opcion',
            name='CA_CETIQUETA',
        ),
        migrations.RemoveField(
            model_name='campo_opcion',
            name='CA_CVALOR',
        ),
        migrations.AddField(
            model_name='campo',
            name='CA_BVALIDARSAP',
            field=models.BooleanField(default=False, verbose_name='Validar contra SAP'),
        ),
        migrations.AddField(
            model_name='campo_opcion',
            name='CA_CNOMBRECAMPO',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Nombre campo'),
        ),
        migrations.AddField(
            model_name='campo_opcion',
            name='CA_CTABLA',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Tabla'),
        ),
        migrations.AddField(
            model_name='etapa',
            name='ET_BINTEGRARSAP',
            field=models.BooleanField(default=False, verbose_name='Integrar SAP'),
        ),
        migrations.AddField(
            model_name='etapa',
            name='ET_CNUMEROOBJETOSAP',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Numero objeto SAP'),
        ),
    ]
