# Generated by Django 5.0.4 on 2024-06-11 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_extra_proforma_epr_bhabilitado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ETAPA_LOG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EL_FFECHAINICIO', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('EL_FFECHAFIN', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('CI_NID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.citacion', verbose_name='Id citación')),
                ('EP_NID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.empresa', verbose_name='Id empresa')),
                ('ET_NID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.etapa', verbose_name='Id etapa')),
                ('SC_NID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.secuencia', verbose_name='Id secuencia')),
            ],
            options={
                'db_table': 'ETAPA_LOG',
            },
        ),
    ]
