# Generated by Django 5.0.4 on 2024-06-10 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_remove_campo_opcion_ca_cetiqueta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapa',
            name='ET_CENDPOINT',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='End point'),
        ),
    ]
