# Generated by Django 3.2.6 on 2024-06-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_etapa_et_ctipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_etapa',
            name='DET_NPASO',
            field=models.IntegerField(blank=True, null=True, verbose_name='Numero paso'),
        ),
    ]
