# Generated by Django 5.0.4 on 2024-06-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_etapa_et_cendpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapa',
            name='ET_BISCABECERA',
            field=models.BooleanField(default=False, verbose_name='Es cabecera'),
        ),
        migrations.AddField(
            model_name='etapa',
            name='ET_BISLINEA',
            field=models.BooleanField(default=False, verbose_name='Es linea'),
        ),
    ]
