# Generated by Django 5.0.4 on 2024-06-12 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_etapa_log'),
        ('home', '0019_alter_detalle_etapa_det_npaso'),
    ]

    operations = [
    ]
