# Generated by Django 5.0.4 on 2024-06-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_etapa_et_biscabecera_etapa_et_bislinea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campo',
            name='CA_CMOTORSQL',
        ),
        migrations.AddField(
            model_name='campo',
            name='CA_CCODIGO',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Codigo'),
        ),
    ]
