# Generated by Django 5.0.2 on 2024-06-11 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_detalle_etapa_det_npaso'),
        ('home', '0021_remove_campo_ca_cmotorsql_campo_ca_ccodigo'),
    ]

    operations = [
    ]
