# Generated by Django 5.0.4 on 2024-06-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_merge_20240611_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapa',
            name='ET_NID_REF',
            field=models.IntegerField(blank=True, null=True, verbose_name='Id etapa referencia'),
        ),
    ]
