# Generated by Django 5.0.4 on 2024-06-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_etapa_et_nid_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapa',
            name='ET_CNOMBREOBJETOSAP',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Nombre objeto SAP'),
        ),
    ]
