# Generated by Django 5.0.4 on 2024-06-12 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_etapa_et_cnombreobjetosap'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZONA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ZON_CLATITUD', models.CharField(max_length=128, verbose_name='Latitud')),
                ('ZON_CLONGITUD', models.CharField(max_length=128, verbose_name='Longitud')),
                ('ZON_CDESCRIPCION', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
                ('ZON_BHABILITADO', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('EP_NID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.empresa', verbose_name='Id empresa')),
                ('ET_NID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.etapa', verbose_name='Id etapa')),
            ],
            options={
                'db_table': 'ZONA',
            },
        ),
    ]
