# Generated by Django 5.0.4 on 2024-06-12 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_zona'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapa',
            name='ZON_NID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.zona', verbose_name='Id zona'),
        ),
    ]
