# Generated by Django 5.0.4 on 2024-06-12 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_etapa_zon_nid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zona',
            name='ET_NID',
        ),
    ]
