# Generated by Django 5.0.4 on 2024-06-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_remove_zona_et_nid'),
    ]

    operations = [
        migrations.AddField(
            model_name='zona',
            name='ZON_CNOMBRE',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Nombre'),
        ),
    ]
