# Generated by Django 5.0.4 on 2024-06-12 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_etapa_log'),
        ('home', '0028_zona_zon_cnombre'),
    ]

    operations = [
    ]
