# Generated by Django 5.0.4 on 2024-06-12 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_merge_0018_etapa_log_0028_zona_zon_cnombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapa',
            name='ET_NID_REF_ADICIONALES',
            field=models.IntegerField(blank=True, null=True, verbose_name='Id etapa referencia adicionales'),
        ),
    ]
