# Generated by Django 5.0.4 on 2024-06-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_etapa_et_nid_ref_adicionales'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapa',
            name='ET_BISADICIONAL',
            field=models.BooleanField(default=False, verbose_name='Es adicional'),
        ),
    ]
