# Generated by Django 5.0.4 on 2024-06-12 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_merge_20240612_1129'),
        ('home', '0031_etapa_et_bisadicional'),
    ]

    operations = [
    ]
