# Generated by Django 5.0.4 on 2024-06-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_merge_20240612_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_secuencia',
            name='SE_BOBLIGATORIO',
            field=models.BooleanField(default=False, verbose_name='Obligatorio'),
        ),
    ]
