# Generated by Django 5.0.4 on 2024-06-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_detalle_secuencia_se_bobligatorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='citacion',
            name='CI_CNUMERODOCUMENTO',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Numero documento'),
        ),
        migrations.AddField(
            model_name='citacion',
            name='CI_CTIPODOCUMENTO',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Tipo documento'),
        ),
    ]
