# Generated by Django 5.0.4 on 2024-06-13 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_citacion_ci_cnumerodocumento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='citacion',
            name='PRO_NID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='citaciones_as_proveedor', to='home.socionegocio', verbose_name='Id proveedor'),
        ),
        migrations.AlterField(
            model_name='citacion',
            name='SN_NID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='citaciones_as_negocio', to='home.socionegocio', verbose_name='Id socio negocio'),
        ),
    ]
