# Generated by Django 5.0.4 on 2024-06-13 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_citacion_pro_nid_alter_citacion_sn_nid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secuencia',
            name='SE_CTIPO',
            field=models.CharField(choices=[('RECEPCION', 'Recepción'), ('DESPACHO', 'Despacho')], max_length=128, verbose_name='Tipo'),
        ),
    ]
