# Generated by Django 5.0.4 on 2024-06-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_alter_secuencia_se_ctipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='citacion',
            name='CI_NID_REF',
            field=models.IntegerField(blank=True, null=True, verbose_name='Id citacion original'),
        ),
    ]
