# Generated by Django 5.0.4 on 2024-06-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_citacion_ci_nid_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='citacion',
            name='CI_CTIPO',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Tipo citacion'),
        ),
    ]
