# Generated by Django 5.0.4 on 2024-06-18 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_citacion_ci_ctipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='extra',
            name='EXT_CTIPO_CITACION',
            field=models.CharField(blank=True, choices=[('RECEPCION', 'Recepción'), ('DESPACHO', 'Despacho')], max_length=128, null=True, verbose_name='Tipo citacion'),
        ),
    ]
