# Generated by Django 5.0.4 on 2024-06-18 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_extra_ext_ctipo_citacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='proforma',
            name='PRO_CTIPO',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Tipo citacion'),
        ),
    ]
