# Generated by Django 5.0.4 on 2024-06-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_proforma_pro_ctipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zona',
            name='ZON_CLATITUD',
        ),
        migrations.RemoveField(
            model_name='zona',
            name='ZON_CLONGITUD',
        ),
        migrations.AddField(
            model_name='zona',
            name='ZON_CLATITUD1',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Latitud 1'),
        ),
        migrations.AddField(
            model_name='zona',
            name='ZON_CLATITUD2',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Latitud 2'),
        ),
        migrations.AddField(
            model_name='zona',
            name='ZON_CLATITUD3',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Latitud 3'),
        ),
        migrations.AddField(
            model_name='zona',
            name='ZON_CLATITUD4',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Latitud 4'),
        ),
        migrations.AddField(
            model_name='zona',
            name='ZON_CLONGITUD1',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Longitud 1'),
        ),
        migrations.AddField(
            model_name='zona',
            name='ZON_CLONGITUD2',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Longitud 2'),
        ),
        migrations.AddField(
            model_name='zona',
            name='ZON_CLONGITUD3',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Longitud 3'),
        ),
        migrations.AddField(
            model_name='zona',
            name='ZON_CLONGITUD4',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Longitud 4'),
        ),
    ]
