# Generated by Django 5.0.4 on 2024-07-08 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_remove_zona_zon_clatitud_remove_zona_zon_clongitud_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camion',
            name='CAM_CMARCA',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Marca'),
        ),
    ]
