# Generated by Django 5.0.2 on 2024-06-28 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_merge_20240611_1501'),
        ('home', '0041_remove_zona_zon_clatitud_remove_zona_zon_clongitud_and_more'),
    ]

    operations = [
    ]
