# Generated by Django 5.0.2 on 2024-07-08 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_alter_camion_cam_cmarca')
    ]

    operations = [
    ]
