# Generated by Django 5.0.2 on 2024-07-22 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_merge_20240708_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camion',
            name='SN_NID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.socionegocio', verbose_name='Id socio negocio'),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='SN_NID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.socionegocio', verbose_name='Id socio negocio'),
        ),
    ]
