# Generated by Django 5.0.4 on 2024-07-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_alter_camion_sn_nid_alter_conductor_sn_nid'),
    ]

    operations = [
        migrations.AddField(
            model_name='socionegocio',
            name='SN_BGENERICO',
            field=models.BooleanField(default=False, verbose_name='Es generico'),
        ),
    ]
