# Generated by Django 5.0.4 on 2024-07-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_socionegocio_sn_bgenerico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socionegocio',
            name='SN_CCODIGO_SAP',
            field=models.CharField(max_length=128, null=True, verbose_name='Codigo SAP'),
        ),
    ]
