# Generated by Django 5.0.4 on 2024-07-24 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_alter_socionegocio_sn_ccodigo_sap'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_secuencia',
            name='USER_RESPONSABLE_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_responsable', to=settings.AUTH_USER_MODEL, verbose_name='id usuario responsable'),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='CON_NPERIODO_EXTRA',
            field=models.IntegerField(default=10, verbose_name='Periodo extra'),
        ),
    ]
