# Generated by Django 5.0.4 on 2024-07-24 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_detalle_secuencia_user_responsable_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NOTIFICACION',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOT_CCONTENIDO', models.TextField(verbose_name='Contenido')),
                ('NOT_CURL', models.URLField(blank=True, null=True, verbose_name='url')),
                ('NOT_BHABILITADO', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('NOT_FFECHAREGISTRO', models.DateTimeField(auto_now_add=True, verbose_name='Fecha registro')),
                ('NOT_FFECHALEIDO', models.DateTimeField(blank=True, null=True, verbose_name='Fecha leido')),
                ('NOT_BREAD', models.BooleanField(default=False, verbose_name='Leido')),
                ('EP_NID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.empresa', verbose_name='Id empresa')),
                ('USER_RECEIVER_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_receiver', to=settings.AUTH_USER_MODEL, verbose_name='id usuario receptor')),
                ('USER_SENDER_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_sender', to=settings.AUTH_USER_MODEL, verbose_name='id usuario emisor')),
            ],
            options={
                'db_table': 'NOTIFICACION',
            },
        ),
    ]
