# Generated by Django 5.0.4 on 2024-07-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_notificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle_secuencia',
            name='USER_RESPONSABLE_ID',
        ),
        migrations.AddField(
            model_name='detalle_secuencia',
            name='USERS_RESPONSABLE_ID',
            field=models.TextField(blank=True, null=True, verbose_name='Usuarios responsables'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='NOT_CURL',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='url'),
        ),
    ]
