# Generated by Django 5.0.4 on 2024-09-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_remove_detalle_secuencia_user_responsable_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planificacion',
            name='PL_BARCHIVADO',
            field=models.BooleanField(default=False, verbose_name='Archivado'),
        ),
    ]
