# Generated by Django 5.0.4 on 2024-09-10 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0050_planificacion_pl_barchivado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='citacion',
            name='CI_BARCHIVADO',
            field=models.BooleanField(default=False, verbose_name='Archivado'),
        ),
        migrations.AddField(
            model_name='planificacion',
            name='PL_FFECHAARCHIVADO',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de archivado'),
        ),
        migrations.AddField(
            model_name='planificacion',
            name='US_ARCHIVADOR_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Usuario_archivador_id', to=settings.AUTH_USER_MODEL, verbose_name='Usuario archivador'),
        ),
    ]
