# Generated by Django 5.0.4 on 2024-09-12 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0051_citacion_ci_barchivado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planificacion',
            name='PL_CTIPOCUPO',
            field=models.CharField(choices=[('RECEPCION', 'Recepción'), ('DESPACHO', 'Despacho')], max_length=128, verbose_name='Tipo de cupo'),
        ),
        migrations.CreateModel(
            name='CUPO_PROVEEDOR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CUP_NCUPOS', models.IntegerField(verbose_name='Cupos')),
                ('CUP_BSOBRECUPO', models.BooleanField(default=False, verbose_name='Sobre cupo')),
                ('CUP_FFECHAREGISTRO', models.DateTimeField(auto_now_add=True, verbose_name='Fecha registro')),
                ('EP_NID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.empresa', verbose_name='Id empresa')),
                ('PLA_NID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.planificacion', verbose_name='Id planificacion')),
                ('PRO_NID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.socionegocio', verbose_name='Id socionegocio')),
            ],
            options={
                'db_table': 'CUPO_PROVEEDOR',
            },
        ),
    ]
