# Generated by Django 5.0.4 on 2024-09-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0052_alter_planificacion_pl_ctipocupo_cupo_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='citacion',
            name='CI_BSOBRECUPO',
            field=models.BooleanField(default=False, verbose_name='Sobre cupo'),
        ),
    ]
