# Generated by Django 5.0.4 on 2024-09-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0053_citacion_ci_bsobrecupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='zona',
            name='ZON_CCOLOR',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Color'),
        ),
    ]
