# Generated by Django 5.0.4 on 2024-09-26 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0054_zona_zon_ccolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='campo',
            name='CA_BASIGNARVALOR',
            field=models.BooleanField(default=False, verbose_name='Asignar valor en bd'),
        ),
    ]
