# Generated by Django 5.0.4 on 2024-10-15 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0055_campo_ca_basignarvalor'),
    ]

    operations = [
        migrations.AddField(
            model_name='zona',
            name='ZON_NCANTIDADCUPOS',
            field=models.IntegerField(null=True, verbose_name='Cantidad de cupos'),
        ),
    ]
