# Generated by Django 5.1.6 on 2025-03-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0056_zona_zon_ncantidadcupos'),
    ]

    operations = [
        migrations.AddField(
            model_name='users_extension',
            name='UX_IS_ADMINISTRADOR_CONDUCTOR',
            field=models.BooleanField(default=False, verbose_name='Es administrador de conductor'),
        ),
    ]
