# Generated by Django 5.1.4 on 2025-05-30 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_merge_20240628_1423'),
        ('home', '0057_users_extension_ux_is_administrador_conductor'),
    ]

    operations = [
    ]
