# Generated by Django 5.0.2 on 2025-03-18 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_merge_20240628_1423'),
        ('home', '0057_users_extension_ux_is_administrador_conductor'),
    ]

    operations = [
    ]
