# Generated by Django 5.0.2 on 2025-06-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0058_merge_20250610_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='proforma',
            name='PRO_BBORRADOR',
            field=models.BooleanField(default=True, verbose_name='Borrador'),
        ),
        migrations.AddField(
            model_name='proforma',
            name='PRO_DOC_ENTRY',
            field=models.IntegerField(blank=True, null=True, verbose_name='DocEntry'),
        ),
        migrations.AddField(
            model_name='proforma',
            name='PRO_DOC_NUM',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='DocNum'),
        ),
        migrations.AddField(
            model_name='proforma',
            name='PRO_FOLIO',
            field=models.IntegerField(blank=True, null=True, verbose_name='Folio'),
        ),
    ]
