# Generated by Django 5.1.4 on 2025-06-09 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0058_merge_20250530_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_secuencia',
            name='SE_FFECHAELIMICACION',
            field=models.DateTimeField(null=True, verbose_name='Fecha de Eliminacion'),
        ),
    ]
