# Generated by Django 5.0.2 on 2025-06-02 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0058_merge_20250318_1705'),
        ('home', '0058_merge_20250530_1208'),
    ]

    operations = [
    ]
