# Generated by Django 5.1.4 on 2025-08-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0059_detalle_secuencia_se_ffechaelimicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='citacion',
            name='CI_BCONFORME',
            field=models.BooleanField(default=False, verbose_name='Entrega conforme'),
        ),
    ]
