# Generated by Django 5.0.2 on 2025-06-10 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0059_proforma_pro_bborrador_proforma_pro_doc_entry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='citacion',
            name='CI_CTIPO_FLETE',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Tipo flete'),
        ),
        migrations.AddField(
            model_name='extra',
            name='EXT_CARTICULOSAP',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Articulos SAP'),
        ),
    ]
