# Generated by Django 5.0.2 on 2025-06-11 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0059_detalle_secuencia_se_ffechaelimicacion'),
        ('home', '0059_merge_20250602_0929'),
    ]

    operations = [
    ]
