# Generated by Django 5.0.2 on 2025-08-11 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0060_citacion_ci_bconforme'),
        ('home', '0060_merge_20250611_0908'),
    ]

    operations = [
    ]
