# Generated by Django 5.0.2 on 2025-06-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0060_citacion_ci_ctipo_flete_extra_ext_carticulosap'),
    ]

    operations = [
        migrations.AddField(
            model_name='extra',
            name='EXT_CCUENTASAP',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Cuentas SAP'),
        ),
        migrations.AddField(
            model_name='proforma',
            name='PRO_CNUMERO_DOCUMENTO',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Numero documento'),
        ),
    ]
