# Generated by Django 5.0.2 on 2025-08-13 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0060_citacion_ci_bconforme'),
        ('home', '0061_extra_ext_ccuentasap_proforma_pro_cnumero_documento'),
    ]

    operations = [
    ]
