# Generated by Django 5.0.4 on 2025-08-25 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0062_merge_20250813_0927'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifa_global',
            name='MODIFICADO_POR',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='id_usuario_modifcador', to=settings.AUTH_USER_MODEL, verbose_name='Id usuario modificador'),
        ),
    ]
