# Generated by Django 5.0.4 on 2025-08-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0063_tarifa_global_modificado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='proforma',
            name='PRO_BSINEXTRAS',
            field=models.BooleanField(default=False, verbose_name='Sin Extras'),
        ),
        migrations.AddField(
            model_name='proforma',
            name='PRO_BSOLOEXTRAS',
            field=models.BooleanField(default=False, verbose_name='Solo extras'),
        ),
    ]
