# Generated by Django 5.0.4 on 2025-10-15 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0064_proforma_pro_bsinextras_proforma_pro_bsoloextras'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DOCUMENTO_PROFORMA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DP_CNOMBREDOCUMENTO', models.CharField(max_length=128, verbose_name='Nombre documento')),
                ('DP_CRUTADOC', models.CharField(max_length=128, verbose_name='Ruta documento')),
                ('DP_FFECHAREGISTRO', models.DateTimeField(blank=True, null=True, verbose_name='Fecha registro')),
                ('DP_BHABILITADO', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('EP_NID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.empresa', verbose_name='Id empresa')),
                ('PRO_NID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.proforma', verbose_name='id_proforma_documento')),
                ('US_NID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Id usuario creador')),
            ],
            options={
                'db_table': 'DOCUMENTO_PROFORMA',
            },
        ),
    ]
