# Generated by Django 5.0.2 on 2025-08-26 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0061_merge_20250811_1303'),
        ('home', '0064_proforma_pro_bsinextras_proforma_pro_bsoloextras'),
    ]

    operations = [
    ]
