# Generated by Django 5.0.4 on 2025-10-16 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0065_documento_proforma'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LINEA_PROFORMA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LP_CTIPO_ITEM', models.CharField(max_length=128, verbose_name='Tipo Item')),
                ('LP_NCANTIDAD', models.IntegerField(verbose_name='Cantidad')),
                ('LP_NPRECIO_UNITARIO', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Precio unitario')),
                ('LP_CDESCRIPCION', models.CharField(max_length=256, verbose_name='Descripcion')),
                ('LP_FFECHACREACION', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creacion')),
                ('PRO_NID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.proforma', verbose_name='id_proforma_manual')),
                ('US_NID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='usuario_creado_fila')),
            ],
            options={
                'db_table': 'LINEA_PROFORMA',
            },
        ),
    ]
