# Generated by Django 5.0.2 on 2026-01-12 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0066_linea_proforma'),
    ]

    operations = [
        migrations.AddField(
            model_name='dato_operacion',
            name='DO_NPESO',
            field=models.IntegerField(blank=True, null=True, verbose_name='Peso dato'),
        ),
    ]
