# Generated by Django 5.0.4 on 2025-10-20 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0065_merge_20250826_1305'),
        ('home', '0066_linea_proforma'),
    ]

    operations = [
    ]
