# Generated by Django 5.0.2 on 2026-01-15 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0067_dato_operacion_do_npeso'),
        ('home', '0067_merge_0065_merge_20250826_1305_0066_linea_proforma'),
    ]

    operations = [
    ]
