# Generated by Django 5.0.2 on 2026-05-11 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0068_merge_20260115_1547'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='users_empresa',
            name='unique_us_nid',
        ),
        migrations.AlterField(
            model_name='users_empresa',
            name='US_NID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas_asignadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='users_empresa',
            constraint=models.UniqueConstraint(fields=('US_NID', 'EP_NID'), name='unique_usuario_empresa'),
        ),
    ]
