# Generated by Django 5.0.2 on 2026-05-11 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0069_remove_users_empresa_unique_us_nid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SAP_OPOR_PROGRAMACION',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SOP_DOCENTRY', models.CharField(max_length=50)),
                ('SOP_DOCNUM', models.CharField(max_length=50)),
                ('SOP_DOCSTATUS', models.CharField(blank=True, max_length=10, null=True)),
                ('SOP_CARDCODE', models.CharField(blank=True, max_length=50, null=True)),
                ('SOP_CARDNAME', models.CharField(blank=True, max_length=255, null=True)),
                ('SOP_DOCDATE', models.DateTimeField(blank=True, null=True)),
                ('SOP_TAXDATE', models.DateTimeField(blank=True, null=True)),
                ('SOP_DOCDUEDATE', models.DateTimeField(blank=True, null=True)),
                ('SOP_CREATEDATE', models.DateTimeField(blank=True, null=True)),
                ('SOP_ITEMCODE', models.CharField(blank=True, max_length=50, null=True)),
                ('SOP_DSCRIPTIONS', models.CharField(blank=True, max_length=255, null=True)),
                ('SOP_OPENQTY', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('SOP_CONTENEDOR', models.CharField(blank=True, max_length=100, null=True)),
                ('SOP_PRODUCTOR', models.CharField(blank=True, max_length=255, null=True)),
                ('SOP_BHABILITADO', models.BooleanField(default=True)),
                ('SOP_FFECHAREGISTRO', models.DateTimeField(auto_now_add=True)),
                ('SOP_FFECHAACTUALIZACION', models.DateTimeField(auto_now=True)),
                ('EP_NID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.empresa', verbose_name='Empresa')),
            ],
            options={
                'db_table': 'SAP_OPOR_PROGRAMACION',
            },
        ),
        migrations.AddConstraint(
            model_name='sap_opor_programacion',
            constraint=models.UniqueConstraint(fields=('EP_NID', 'SOP_DOCENTRY', 'SOP_ITEMCODE'), name='unique_sap_opor_empresa_docentry_item'),
        ),
    ]
