# Generated by Django 5.0.2 on 2026-05-19 20:04

import apps.home.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0071_planificacion_pl_ncantidadsobrecupo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CAMION_NO_PLANIFICADO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CLI_CCODIGO', models.CharField(blank=True, max_length=128, null=True, verbose_name='Codigo cliente')),
                ('CLI_CNOMBRE', models.CharField(max_length=256, verbose_name='Cliente')),
                ('CNP_CINSUMO', models.CharField(max_length=256, verbose_name='Insumo')),
                ('CNP_CNUMEROGUIA', models.CharField(max_length=128, verbose_name='Numero guia')),
                ('CNP_CPATENTE', models.CharField(max_length=32, verbose_name='Patente')),
                ('CNP_CEMPRESATRANSPORTE', models.CharField(max_length=256, verbose_name='Empresa transporte')),
                ('CNP_COBSERVACION', models.TextField(blank=True, null=True, verbose_name='Observacion')),
                ('CNP_FARCHIVOGUIA', models.FileField(upload_to=apps.home.models.camion_no_planificado_upload_path, verbose_name='Archivo guia')),
                ('CNP_CESTADO', models.CharField(choices=[('PENDIENTE_REVISION', 'Pendiente de revision'), ('PLANIFICADO', 'Planificado'), ('RECHAZADO', 'Rechazado'), ('CORRECCION_SOLICITADA', 'Correccion solicitada')], default='PENDIENTE_REVISION', max_length=32, verbose_name='Estado')),
                ('CNP_COBSERVACION_RECHAZO', models.TextField(blank=True, null=True, verbose_name='Observacion rechazo')),
                ('CNP_FFECHACREACION', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creacion')),
                ('CNP_FFECHARESPUESTA', models.DateTimeField(blank=True, null=True, verbose_name='Fecha respuesta')),
                ('EP_NID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.empresa', verbose_name='Id empresa')),
                ('PL_NID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.planificacion', verbose_name='Id planificacion')),
                ('US_GUARDIA_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='camiones_no_planificados_solicitados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario guardia')),
                ('US_PLANIFICADOR_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='camiones_no_planificados_resueltos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario planificador')),
            ],
            options={
                'db_table': 'CAMION_NO_PLANIFICADO',
                'indexes': [models.Index(fields=['EP_NID', 'PL_NID', 'CNP_CPATENTE', 'CNP_CESTADO'], name='CAMION_NO_P_EP_NID__100d31_idx')],
            },
        ),
    ]
