# Generated by Django 5.0.2 on 2026-05-20 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0072_camion_no_planificado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='etapa_log',
            name='EL_CACCION',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Accion'),
        ),
        migrations.AddField(
            model_name='etapa_log',
            name='EL_COBSERVACION',
            field=models.TextField(blank=True, null=True, verbose_name='Observacion'),
        ),
        migrations.AddField(
            model_name='etapa_log',
            name='US_FIN_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='etapas_log_fin', to=settings.AUTH_USER_MODEL, verbose_name='Usuario fin etapa'),
        ),
        migrations.AddField(
            model_name='etapa_log',
            name='US_INICIO_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='etapas_log_inicio', to=settings.AUTH_USER_MODEL, verbose_name='Usuario inicio etapa'),
        ),
    ]
