# Generated by Codex on 2026-05-26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0074_citacion_detalle_operacional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ESTANQUE_RESERVA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ER_CALMACEN', models.CharField(max_length=128, verbose_name='Almacen')),
                ('ER_CESTANQUE', models.CharField(max_length=128, verbose_name='Estanque')),
                ('ER_CPATENTE', models.CharField(blank=True, max_length=128, null=True, verbose_name='Patente')),
                ('ER_CESTADO', models.CharField(choices=[('OCUPADO', 'Ocupado'), ('LIBERADO', 'Liberado')], default='OCUPADO', max_length=32, verbose_name='Estado reserva')),
                ('ER_FFECHA_ASIGNACION', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha asignacion')),
                ('ER_FFECHA_LIBERACION', models.DateTimeField(blank=True, null=True, verbose_name='Fecha liberacion')),
                ('ER_COBSERVACION', models.TextField(blank=True, null=True, verbose_name='Observacion')),
                ('CI_NID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.citacion', verbose_name='Citacion')),
                ('EP_NID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.empresa', verbose_name='Empresa')),
                ('PL_NID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.planificacion', verbose_name='Planificacion')),
                ('US_LIBERA_NID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estanques_liberados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario liberacion')),
                ('US_NID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario asignacion')),
            ],
            options={
                'db_table': 'ESTANQUE_RESERVA',
            },
        ),
        migrations.AddConstraint(
            model_name='estanque_reserva',
            constraint=models.UniqueConstraint(condition=models.Q(('ER_CESTADO', 'OCUPADO')), fields=('EP_NID', 'ER_CALMACEN', 'ER_CESTANQUE'), name='unique_estanque_ocupado_empresa_almacen'),
        ),
    ]
