# Generated by Codex on 2026-05-26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0075_estanque_reserva'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OPERACION_PLANTA_LOG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OPL_CPASO', models.CharField(max_length=128, verbose_name='Paso operacional')),
                ('OPL_CPERFIL_RESPONSABLE', models.CharField(max_length=128, verbose_name='Perfil responsable')),
                ('OPL_CESTADO', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADO', 'Completado')], default='COMPLETADO', max_length=32, verbose_name='Estado')),
                ('OPL_COBSERVACION', models.TextField(blank=True, null=True, verbose_name='Observacion')),
                ('OPL_FFECHAREGISTRO', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha registro')),
                ('CI_NID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.citacion', verbose_name='Citacion')),
                ('EP_NID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.empresa', verbose_name='Empresa')),
                ('PL_NID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.planificacion', verbose_name='Planificacion')),
                ('US_NID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'db_table': 'OPERACION_PLANTA_LOG',
            },
        ),
    ]
