# Generated by Codex on 2026-06-16

import apps.home.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0077_citacion_documento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CAMION_PATIO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CPA_CPATENTE', models.CharField(max_length=32, verbose_name='Patente camion')),
                ('CPA_CPATENTE_RAMPLA', models.CharField(blank=True, max_length=32, null=True, verbose_name='Patente rampla/acoplado')),
                ('CPA_CNOMBRE_CONDUCTOR', models.CharField(max_length=256, verbose_name='Nombre conductor')),
                ('CPA_CRUT_CONDUCTOR', models.CharField(blank=True, max_length=32, null=True, verbose_name='RUT conductor')),
                ('CPA_CTELEFONO_CONDUCTOR', models.CharField(blank=True, max_length=64, null=True, verbose_name='Telefono conductor')),
                ('CPA_CTRANSPORTISTA_DECLARADO', models.CharField(blank=True, max_length=256, null=True, verbose_name='Transportista declarado')),
                ('CPA_CPROVEEDOR_DECLARADO', models.CharField(blank=True, max_length=256, null=True, verbose_name='Proveedor declarado')),
                ('CPA_CPRODUCTO_DECLARADO', models.CharField(blank=True, max_length=256, null=True, verbose_name='Producto declarado')),
                ('CPA_CCLIENTE_DECLARADO', models.CharField(blank=True, max_length=256, null=True, verbose_name='Cliente declarado')),
                ('CPA_CNUMERO_GUIA', models.CharField(blank=True, max_length=128, null=True, verbose_name='Numero guia/documento')),
                ('CPA_COBSERVACION', models.TextField(blank=True, null=True, verbose_name='Observacion')),
                ('CPA_CESTADO', models.CharField(choices=[('PENDIENTE_ASOCIACION', 'Pendiente asociacion'), ('EN_REVISION_RECEPCION', 'En revision recepcion'), ('ASOCIADO_CITACION', 'Asociado a citacion'), ('RECHAZADO', 'Rechazado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE_ASOCIACION', max_length=32, verbose_name='Estado')),
                ('CPA_FFECHALLEGADA', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha/hora llegada')),
                ('CPA_FFECHACREACION', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creacion')),
                ('CPA_FFECHAACTUALIZACION', models.DateTimeField(auto_now=True, verbose_name='Fecha actualizacion')),
                ('CPA_FFECHAASOCIACION', models.DateTimeField(blank=True, null=True, verbose_name='Fecha asociacion')),
                ('CI_NID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='camiones_patio', to='home.citacion', verbose_name='Citacion asociada')),
                ('EP_NID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.empresa', verbose_name='Empresa')),
                ('US_ASOCIA_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='camiones_patio_asociados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario asocia')),
                ('US_GUARDIA_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='camiones_patio_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario guardia')),
            ],
            options={
                'db_table': 'CAMION_PATIO',
            },
        ),
        migrations.CreateModel(
            name='CAMION_PATIO_ADJUNTO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CPA_FARCHIVO', models.FileField(upload_to=apps.home.models.camion_patio_upload_path, verbose_name='Archivo')),
                ('CPA_CTIPO_DOCUMENTO', models.CharField(choices=[('GUIA', 'Guia'), ('TICKET_ORIGEN', 'Ticket origen'), ('SERNAPESCA', 'Sernapesca'), ('OTRO', 'Otro')], default='OTRO', max_length=64, verbose_name='Tipo documento')),
                ('CPA_FFECHACARGA', models.DateTimeField(auto_now_add=True, verbose_name='Fecha carga')),
                ('CPA_NID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='home.camion_patio', verbose_name='Camion patio')),
                ('US_CARGA_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='camiones_patio_adjuntos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario carga')),
            ],
            options={
                'db_table': 'CAMION_PATIO_ADJUNTO',
            },
        ),
        migrations.AddIndex(
            model_name='camion_patio',
            index=models.Index(fields=['EP_NID', 'CPA_CESTADO'], name='CAM_PATIO_EP_EST_idx'),
        ),
        migrations.AddIndex(
            model_name='camion_patio',
            index=models.Index(fields=['EP_NID', 'CPA_CPATENTE'], name='CAM_PATIO_EP_PAT_idx'),
        ),
        migrations.AddIndex(
            model_name='camion_patio',
            index=models.Index(fields=['CI_NID'], name='CAM_PATIO_CIT_idx'),
        ),
        migrations.AddIndex(
            model_name='camion_patio_adjunto',
            index=models.Index(fields=['CPA_NID', 'CPA_CTIPO_DOCUMENTO'], name='CAM_PAT_ADJ_TIPO_idx'),
        ),
    ]
