# Generated by Codex on 2026-06-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0078_camion_patio_camion_patio_adjunto'),
    ]

    operations = [
        migrations.AddField(
            model_name='camion_patio',
            name='CPA_CINSUMO_DECLARADO_GUIA',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Insumo declarado en guia'),
        ),
        migrations.AddField(
            model_name='camion_patio',
            name='CPA_CBL',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='BL'),
        ),
        migrations.AddField(
            model_name='camion_patio',
            name='CPA_CCANTIDAD_EJES',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Cantidad de ejes'),
        ),
        migrations.AddField(
            model_name='camion_patio',
            name='CPA_CLOTE_CONTENEDOR',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Lote/contenedor'),
        ),
    ]
