# Generated by Django 5.0.2 on 2026-06-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0080_citacion_despacho_detalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='citacion',
            name='CI_INTERMES_ID',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='ID Intermes'),
        ),
    ]
