# Generated by Django 5.0.2 on 2026-06-25 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0081_citacion_ci_intermes_id_alter_citacion_documento_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citacion',
            name='CI_INTERMES_ID',
        ),
    ]
