# Generated by Django 5.0.2 on 2026-07-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0082_remove_citacion_ci_intermes_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='citacion_despacho_detalle',
            name='CDD_CSALIDA_DOCUMENTO',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Salida de documento'),
        ),
    ]
