# Generated by Django 5.0.2 on 2026-07-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0083_citacion_despacho_detalle_cdd_csalida_documento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='citacion_despacho_detalle',
            name='CDD_NPESO_INFORMADO',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=18, null=True, verbose_name='Peso informado'),
        ),
    ]
