# Generated by Django 5.0.2 on 2026-07-13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0088_camion_patio_transporte_a_cargo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CAMION_PATIO_NO_PLANIFICADO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CPNP_CESTADO', models.CharField(choices=[('PENDIENTE', 'Pendiente de revision'), ('APROBADO_PENDIENTE_PLANIFICACION', 'Aprobado pendiente de planificacion'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=50, verbose_name='Estado')),
                ('CPNP_FFECHASOLICITUD', models.DateTimeField(auto_now_add=True, verbose_name='Fecha solicitud')),
                ('CPNP_FFECHARESOLUCION', models.DateTimeField(blank=True, null=True, verbose_name='Fecha resolucion')),
                ('CPNP_CMOTIVO_RECHAZO', models.TextField(blank=True, verbose_name='Motivo rechazo')),
                ('CPNP_BTEAMS_ENVIADO', models.BooleanField(default=False, verbose_name='Teams enviado')),
                ('CPNP_CTEAMS_ESTADO', models.CharField(blank=True, max_length=50, verbose_name='Estado Teams')),
                ('CPNP_CTEAMS_DETALLE', models.TextField(blank=True, verbose_name='Detalle Teams')),
                ('CPA_NID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_no_planificado', to='home.camion_patio', verbose_name='Camion patio')),
                ('EP_NID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.empresa', verbose_name='Empresa')),
                ('PL_NID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_camion_patio_no_planificado', to='home.planificacion', verbose_name='Planificacion creada')),
                ('US_PLANIFICADOR_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='camiones_patio_no_planificados_resueltos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario planificador')),
                ('US_SOLICITA_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='camiones_patio_no_planificados_solicitados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario solicitante')),
            ],
            options={
                'db_table': 'CAMION_PATIO_NO_PLANIFICADO',
                'indexes': [models.Index(fields=['EP_NID', 'CPNP_CESTADO'], name='CAM_PAT_NP_EP_EST_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='camion_patio_no_planificado',
            constraint=models.UniqueConstraint(condition=models.Q(('CPNP_CESTADO', 'PENDIENTE')), fields=('CPA_NID',), name='uniq_cam_pat_no_plan_pendiente'),
        ),
    ]
