# Generated by Django 5.0.2 on 2026-07-21 14:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0091_citacion_numero_documento_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RESULTADO_CALIDAD_OPERACION',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RCO_CNUMERO_GUIA', models.CharField(blank=True, db_index=True, max_length=128, null=True, verbose_name='Numero de guia')),
                ('RCO_CESTADO', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('APRUEBA_CLIENTE', 'Aprueba cliente')], default='PENDIENTE', max_length=32, verbose_name='Estado actual')),
                ('RCO_CORIGEN', models.CharField(choices=[('OPERACION_PLANTA', 'Operacion Planta'), ('EXCEL_CALIDAD', 'Excel Calidad'), ('CORREO_CLIENTE', 'Correo cliente'), ('MANUAL_PRUEBA', 'Manual / prueba')], default='OPERACION_PLANTA', max_length=32, verbose_name='Origen actualizacion')),
                ('RCO_FINICIO', models.DateTimeField(verbose_name='Inicio analisis')),
                ('RCO_FACTUALIZACION', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ultimo cambio')),
                ('RCO_FDETENCION_TEMPORIZADOR', models.DateTimeField(blank=True, null=True, verbose_name='Detencion temporizador')),
                ('RCO_FSOLICITUD_CLIENTE', models.DateTimeField(blank=True, null=True, verbose_name='Solicitud aprobacion cliente')),
                ('RCO_FRESOLUCION_FINAL', models.DateTimeField(blank=True, null=True, verbose_name='Resolucion final')),
                ('RCO_FCIERRE', models.DateTimeField(blank=True, null=True, verbose_name='Cierre definitivo')),
                ('RCO_COBSERVACION', models.TextField(blank=True, null=True, verbose_name='Observacion')),
                ('RCO_CRESPONSABLE_SISTEMA', models.CharField(blank=True, max_length=128, null=True, verbose_name='Sistema responsable')),
                ('RCO_BCIERRE_AUTOMATICO', models.BooleanField(default=False, verbose_name='Cierre automatico')),
                ('RCO_BAUTORIZA_SALIDA', models.BooleanField(default=False, verbose_name='Autorizacion de salida')),
                ('RCO_NDURACION_SEGUNDOS', models.BigIntegerField(default=0, verbose_name='Duracion acumulada analisis')),
                ('CA_NID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.camion', verbose_name='Patente / camion')),
                ('CI_NID', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='resultado_calidad_operacion', to='home.citacion', verbose_name='Citacion')),
                ('EP_NID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.empresa', verbose_name='Empresa')),
                ('ET_NID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.etapa', verbose_name='Etapa operacional')),
                ('PL_NID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.planificacion', verbose_name='Proceso Operacion Planta')),
                ('US_NID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario responsable')),
            ],
            options={
                'db_table': 'RESULTADO_CALIDAD_OPERACION',
            },
        ),
        migrations.CreateModel(
            name='RESULTADO_CALIDAD_HISTORIAL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RCH_CEVENTO', models.CharField(max_length=64, verbose_name='Evento')),
                ('RCH_CESTADO_ANTERIOR', models.CharField(blank=True, max_length=32, null=True, verbose_name='Estado anterior')),
                ('RCH_CESTADO_NUEVO', models.CharField(max_length=32, verbose_name='Estado nuevo')),
                ('RCH_CORIGEN', models.CharField(choices=[('OPERACION_PLANTA', 'Operacion Planta'), ('EXCEL_CALIDAD', 'Excel Calidad'), ('CORREO_CLIENTE', 'Correo cliente'), ('MANUAL_PRUEBA', 'Manual / prueba')], max_length=32, verbose_name='Origen')),
                ('RCH_CRESULTADO', models.CharField(blank=True, max_length=32, null=True, verbose_name='Resultado')),
                ('RCH_COBSERVACION', models.TextField(blank=True, null=True, verbose_name='Observacion')),
                ('RCH_CRESPONSABLE_SISTEMA', models.CharField(blank=True, max_length=128, null=True, verbose_name='Sistema responsable')),
                ('RCH_FFECHAREGISTRO', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha registro')),
                ('CI_NID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.citacion', verbose_name='Citacion')),
                ('EP_NID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.empresa', verbose_name='Empresa')),
                ('US_NID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario responsable')),
                ('RCO_NID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='home.resultado_calidad_operacion', verbose_name='Resultado calidad')),
            ],
            options={
                'db_table': 'RESULTADO_CALIDAD_HISTORIAL',
            },
        ),
        migrations.AddIndex(
            model_name='resultado_calidad_operacion',
            index=models.Index(fields=['EP_NID', 'RCO_CNUMERO_GUIA'], name='RCO_EP_GUIA_IDX'),
        ),
        migrations.AddIndex(
            model_name='resultado_calidad_operacion',
            index=models.Index(fields=['EP_NID', 'RCO_CESTADO'], name='RCO_EP_ESTADO_IDX'),
        ),
        migrations.AddIndex(
            model_name='resultado_calidad_historial',
            index=models.Index(fields=['CI_NID', 'RCH_FFECHAREGISTRO'], name='RCH_CI_FECHA_IDX'),
        ),
    ]
