# Generated by Django 5.0.2 on 2026-07-21 14:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0092_alter_citacion_documento_cd_ctipo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EVENTO_INTEGRACION_CALIDAD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EIC_CID_EVENTO', models.CharField(max_length=128, unique=True, verbose_name='Id evento externo')),
                ('EIC_CNUMERO_GUIA', models.CharField(db_index=True, max_length=128, verbose_name='Numero de guia')),
                ('EIC_CESTADO_SOLICITADO', models.CharField(max_length=32, verbose_name='Estado solicitado')),
                ('EIC_CORIGEN', models.CharField(max_length=32, verbose_name='Origen')),
                ('EIC_FRESULTADO', models.DateTimeField(blank=True, null=True, verbose_name='Fecha resultado externo')),
                ('EIC_FRECEPCION', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha recepcion')),
                ('EIC_FPROCESAMIENTO', models.DateTimeField(blank=True, null=True, verbose_name='Fecha procesamiento')),
                ('EIC_CESTADO_PROCESAMIENTO', models.CharField(choices=[('RECIBIDO', 'Recibido'), ('PROCESADO', 'Procesado'), ('DUPLICADO', 'Duplicado'), ('ERROR_VALIDACION', 'Error validacion'), ('ERROR_PROCESAMIENTO', 'Error procesamiento')], default='RECIBIDO', max_length=32, verbose_name='Estado procesamiento')),
                ('EIC_CRESULTADO', models.CharField(blank=True, max_length=128, null=True, verbose_name='Resultado procesamiento')),
                ('EIC_CMENSAJE_TECNICO', models.TextField(blank=True, null=True, verbose_name='Mensaje tecnico')),
                ('EIC_CPAYLOAD_SANITIZADO', models.TextField(blank=True, null=True, verbose_name='Payload sanitizado')),
                ('EIC_NCODIGO_RESPUESTA', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Codigo respuesta')),
                ('EIC_BDUPLICADO', models.BooleanField(default=False, verbose_name='Evento duplicado recibido')),
                ('EIC_BTEAMS_PENDIENTE', models.BooleanField(default=False, verbose_name='Teams pendiente')),
                ('EIC_BTEAMS_ENVIADO', models.BooleanField(default=False, verbose_name='Teams enviado')),
                ('EIC_CESTADO_TEAMS', models.CharField(choices=[('NO_APLICA', 'No aplica'), ('PENDIENTE', 'Pendiente'), ('ENVIANDO', 'Enviando'), ('ENVIADO', 'Enviado'), ('ERROR', 'Error')], default='NO_APLICA', max_length=32, verbose_name='Estado Teams')),
                ('EIC_NINTENTOS_TEAMS', models.PositiveSmallIntegerField(default=0, verbose_name='Intentos Teams')),
                ('EIC_FULTIMO_INTENTO_TEAMS', models.DateTimeField(blank=True, null=True, verbose_name='Ultimo intento Teams')),
                ('EIC_CERROR_TEAMS', models.TextField(blank=True, null=True, verbose_name='Error Teams sanitizado')),
                ('CI_NID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.citacion', verbose_name='Citacion')),
                ('EP_NID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.empresa', verbose_name='Empresa')),
                ('RCO_NID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos_integracion', to='home.resultado_calidad_operacion', verbose_name='Proceso calidad')),
            ],
            options={
                'db_table': 'EVENTO_INTEGRACION_CALIDAD',
                'indexes': [models.Index(fields=['EP_NID', 'EIC_CNUMERO_GUIA'], name='EIC_EP_GUIA_IDX'), models.Index(fields=['EIC_CESTADO_TEAMS', 'EIC_BTEAMS_PENDIENTE'], name='EIC_TEAMS_PEND_IDX')],
            },
        ),
    ]
