# Generated by Django 5.0.2 on 2026-07-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0094_camion_patio_tipo_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='camion_patio',
            name='CPA_CCODIGO_PAIS_TELEFONO',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Codigo pais telefono conductor'),
        ),
        migrations.AddField(
            model_name='conductor',
            name='CON_CCODIGO_PAIS_TELEFONO',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Codigo pais telefono'),
        ),
    ]
