# Generated by Django 5.0.2 on 2026-08-03 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0096_citacion_recepcion_terramar_detalle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CAMION_PATIO_TRAZABILIDAD_PLANIFICACION',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CPTR_CPATENTE_CONSULTADA', models.CharField(max_length=32)),
                ('CPTR_CRESULTADO_BUSQUEDA', models.CharField(max_length=32)),
                ('CPTR_BCARGADO_DESDE_PLANIFICACION', models.BooleanField(default=False)),
                ('CPTR_CPATENTE_PLANIFICADA', models.CharField(blank=True, max_length=32)),
                ('CPTR_CPATENTE_LLEGADA', models.CharField(blank=True, max_length=32)),
                ('CPTR_CGUIA_ESPERADA', models.CharField(blank=True, max_length=128)),
                ('CPTR_CGUIA_RECIBIDA', models.CharField(blank=True, max_length=128)),
                ('CPTR_CRESULTADO_GUIA', models.CharField(blank=True, max_length=24)),
                ('CPTR_BDIFERENCIA_ACEPTADA', models.BooleanField(default=False)),
                ('CPTR_COBSERVACION_DIFERENCIA', models.TextField(blank=True)),
                ('CPTR_FFECHACONSULTA', models.DateTimeField(blank=True, null=True)),
                ('CPTR_FFECHAREGISTRO', models.DateTimeField(auto_now_add=True)),
                ('CI_NID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.citacion')),
                ('CPA_NID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trazabilidad_planificacion', to='home.camion_patio')),
                ('EP_NID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.empresa')),
                ('PL_NID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.planificacion')),
                ('US_NID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'CAMION_PATIO_TRAZABILIDAD_PLANIFICACION',
            },
        ),
    ]
