# Generated by Django 5.0.2 on 2026-08-17 03:15

from decimal import Decimal

from django.db import migrations, models


def configurar_extras_terramar(apps, schema_editor):
    Extra = apps.get_model('home', 'EXTRA')
    configuraciones = {
        1: (Decimal('45000'), True, True),
        2: (Decimal('45000'), True, True),
        3: (Decimal('30000'), False, True),
        4: (Decimal('15000'), False, True),
        5: (Decimal('250000'), False, True),
        6: (Decimal('250000'), False, True),
        7: (Decimal('100000'), False, True),
        9: (Decimal('100000'), False, True),
    }
    for extra_id, (valor, permite_cantidad, permite_editar) in configuraciones.items():
        Extra.objects.filter(pk=extra_id, EP_NID_id=1).update(
            EXT_NVALORBASE=valor,
            EXT_BPERMITECANTIDAD=permite_cantidad,
            EXT_BPERMITEEDITARVALOR=permite_editar,
        )


def revertir_configuracion_extras_terramar(apps, schema_editor):
    Extra = apps.get_model('home', 'EXTRA')
    Extra.objects.filter(pk__in=[1, 2, 3, 4, 5, 6, 7, 9], EP_NID_id=1).update(
        EXT_NVALORBASE=None,
        EXT_BPERMITECANTIDAD=None,
        EXT_BPERMITEEDITARVALOR=None,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0102_proforma_periodo_mensual_terramar'),
    ]

    operations = [
        migrations.AddField(
            model_name='citacion_extra',
            name='CIE_NCANTIDAD',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Cantidad'),
        ),
        migrations.AddField(
            model_name='citacion_extra',
            name='CIE_NVALORUNITARIO',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=18, null=True, verbose_name='Valor unitario'),
        ),
        migrations.AddField(
            model_name='extra',
            name='EXT_BPERMITECANTIDAD',
            field=models.BooleanField(blank=True, null=True, verbose_name='Permite cantidad'),
        ),
        migrations.AddField(
            model_name='extra',
            name='EXT_BPERMITEEDITARVALOR',
            field=models.BooleanField(blank=True, null=True, verbose_name='Permite editar valor'),
        ),
        migrations.AddField(
            model_name='extra',
            name='EXT_NVALORBASE',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=18, null=True, verbose_name='Valor base'),
        ),
        migrations.AddField(
            model_name='extra_proforma',
            name='EPR_NCANTIDAD',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Cantidad snapshot'),
        ),
        migrations.AddField(
            model_name='extra_proforma',
            name='EPR_NVALORUNITARIO',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=18, null=True, verbose_name='Valor unitario snapshot'),
        ),
        migrations.RunPython(
            configurar_extras_terramar,
            revertir_configuracion_extras_terramar,
        ),
    ]