# Generated by Django 5.0.2 on 2026-08-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0111_camion_patio_documentos_recepcion_sbh'),
    ]

    operations = [
        migrations.AddField(
            model_name='citacion_detalle_operacional',
            name='CDO_CESTANQUE_ORIGEN',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Estanque origen transferencia'),
        ),
        migrations.AddField(
            model_name='citacion_detalle_operacional',
            name='CDO_CPROPIEDAD_PRODUCTO',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Propiedad producto transferencia'),
        ),
        migrations.AddField(
            model_name='citacion_detalle_operacional',
            name='CDO_NCANTIDAD_A_MOVER',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=18, null=True, verbose_name='Cantidad a mover transferencia'),
        ),
        migrations.AddField(
            model_name='citacion_detalle_operacional',
            name='CDO_NCANTIDAD_CAMION',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=18, null=True, verbose_name='Cantidad camion transferencia'),
        ),
    ]
