# Generated by Django 5.0.2 on 2026-08-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0112_recepcion_transferencia_sbh'),
    ]

    operations = [
        migrations.AddField(
            model_name='citacion_detalle_operacional',
            name='CDO_CCODIGO_PROPIETARIO',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Codigo propietario transferencia'),
        ),
        migrations.AddField(
            model_name='citacion_detalle_operacional',
            name='CDO_CUNIDAD_INVENTARIO',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Unidad inventario transferencia'),
        ),
    ]
