# Generated by Django 5.0.2 on 2026-08-24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0113_recepcion_transferencia_sbh_snapshot_sap'),
    ]

    operations = [
        migrations.CreateModel(
            name='CONDUCTOR_EMPRESA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CEM_BHABILITADO', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('CEM_FFECHAREGISTRO', models.DateTimeField(auto_now_add=True, verbose_name='Fecha registro')),
                ('CON_NID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empresas_operacionales', to='home.conductor', verbose_name='Id conductor')),
                ('EP_NID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conductores_operacionales', to='home.empresa', verbose_name='Id empresa')),
                ('US_NID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario registro')),
            ],
            options={'db_table': 'CONDUCTOR_EMPRESA'},
        ),
        migrations.AddConstraint(
            model_name='conductor_empresa',
            constraint=models.UniqueConstraint(fields=('CON_NID', 'EP_NID'), name='unique_conductor_empresa'),
        ),
    ]
