# Generated by Django 5.0.2 on 2026-09-08 19:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0119_despacho_sbh_programacion_horaria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CITACION_DESPACHO_ASIGNACION_SAP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CDAS_CSAP_ABS_ID', models.CharField(blank=True, max_length=128, null=True, verbose_name='SAP AbsID snapshot')),
                ('CDAS_CSAP_NUMERO_ACUERDO', models.CharField(blank=True, max_length=128, null=True, verbose_name='Numero acuerdo SAP snapshot')),
                ('CDAS_CSAP_LINEA_ACUERDO', models.CharField(blank=True, max_length=128, null=True, verbose_name='Linea acuerdo SAP snapshot')),
                ('CDAS_CSAP_CODIGO_PRODUCTO', models.CharField(blank=True, max_length=128, null=True, verbose_name='Codigo producto SAP snapshot')),
                ('CDAS_CSAP_NOMBRE_PRODUCTO', models.CharField(blank=True, max_length=256, null=True, verbose_name='Nombre producto SAP snapshot')),
                ('CDAS_CSAP_CLIENTE_CODIGO', models.CharField(blank=True, max_length=128, null=True, verbose_name='Codigo cliente SAP snapshot')),
                ('CDAS_CSAP_CLIENTE_NOMBRE', models.CharField(blank=True, max_length=256, null=True, verbose_name='Nombre cliente SAP snapshot')),
                ('CDAS_CSAP_OC_CLIENTE', models.CharField(blank=True, max_length=128, null=True, verbose_name='OC cliente SAP snapshot')),
                ('CDAS_NSAP_CANTIDAD_CONTRATO', models.DecimalField(blank=True, decimal_places=5, max_digits=18, null=True, verbose_name='Cantidad contrato SAP snapshot')),
                ('CDAS_NSAP_CANTIDAD_CONSUMIDA', models.DecimalField(blank=True, decimal_places=5, max_digits=18, null=True, verbose_name='Cantidad consumida SAP snapshot')),
                ('CDAS_NSAP_SALDO', models.DecimalField(blank=True, decimal_places=5, max_digits=18, null=True, verbose_name='Saldo SAP snapshot')),
                ('CDAS_CSAP_UNIDAD_MEDIDA', models.CharField(blank=True, max_length=64, null=True, verbose_name='Unidad medida SAP snapshot')),
                ('CDAS_NCANTIDAD_INTENTADA_DESPACHAR', models.DecimalField(decimal_places=5, max_digits=18, verbose_name='Cantidad intentada a despachar')),
                ('CDAS_NORDEN', models.PositiveIntegerField(verbose_name='Orden de asignacion')),
                ('CDAS_CESTADO', models.CharField(choices=[('PLANIFICADA', 'Planificada'), ('ANULADA', 'Anulada')], default='PLANIFICADA', max_length=16, verbose_name='Estado')),
                ('CDAS_FFECHA_SNAPSHOT', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha snapshot SAP')),
                ('CDAS_FFECHACREACION', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creacion')),
                ('CDAS_FFECHAACTUALIZACION', models.DateTimeField(auto_now=True, verbose_name='Fecha actualizacion')),
                ('CDD_NID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_sap', to='home.citacion_despacho_detalle', verbose_name='Detalle despacho')),
                ('EP_NID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.empresa', verbose_name='Id empresa')),
                ('US_NID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario creacion')),
            ],
            options={
                'db_table': 'CITACION_DESPACHO_ASIGNACION_SAP',
                'ordering': ['CDAS_NORDEN', 'id'],
                'indexes': [models.Index(fields=['EP_NID', 'CDAS_CSAP_ABS_ID'], name='CIT_DESP_SAP_ABS_IDX'), models.Index(fields=['CDAS_CSAP_NUMERO_ACUERDO'], name='CIT_DESP_SAP_NUM_IDX')],
            },
        ),
        migrations.AddConstraint(
            model_name='citacion_despacho_asignacion_sap',
            constraint=models.UniqueConstraint(fields=('CDD_NID', 'CDAS_CSAP_ABS_ID', 'CDAS_CSAP_LINEA_ACUERDO'), name='CIT_DESP_SAP_UNQ_LINEA'),
        ),
        migrations.AddConstraint(
            model_name='citacion_despacho_asignacion_sap',
            constraint=models.UniqueConstraint(fields=('CDD_NID', 'CDAS_NORDEN'), name='CIT_DESP_SAP_UNQ_ORDEN'),
        ),
        migrations.AddConstraint(
            model_name='citacion_despacho_asignacion_sap',
            constraint=models.CheckConstraint(check=models.Q(('CDAS_NCANTIDAD_INTENTADA_DESPACHAR__gt', 0)), name='CIT_DESP_SAP_CANT_POSITIVA'),
        ),
    ]
