# Generated by Django 5.0.2 on 2026-09-10 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0120_citacion_despacho_asignacion_sap'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CITACION_DESPACHO_ACUERDO_ESTANQUE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_code', models.CharField(max_length=64)),
                ('item_code', models.CharField(max_length=128)),
                ('item_name', models.CharField(max_length=256)),
                ('linea_acuerdo', models.CharField(max_length=128)),
                ('unidad_medida', models.CharField(max_length=64)),
                ('cantidad', models.DecimalField(decimal_places=5, max_digits=18)),
                ('orden', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'CITACION_DESPACHO_ACUERDO_TK',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CITACION_DESPACHO_ACUERDO_OPERACIONAL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sap_abs_id', models.PositiveIntegerField()),
                ('numero_acuerdo', models.CharField(max_length=128)),
                ('cliente_codigo', models.CharField(max_length=128)),
                ('cliente_nombre', models.CharField(max_length=256)),
                ('oc_cliente', models.CharField(blank=True, max_length=128)),
                ('cantidad', models.DecimalField(decimal_places=5, max_digits=18)),
                ('orden', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'CITACION_DESPACHO_ACUERDO_OP',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CITACION_DESPACHO_ACUERDO_LOTE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=128)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('stock_snapshot', models.DecimalField(decimal_places=5, max_digits=18)),
                ('cantidad', models.DecimalField(decimal_places=5, max_digits=18)),
                ('estanque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='home.citacion_despacho_acuerdo_estanque')),
            ],
            options={
                'db_table': 'CITACION_DESPACHO_ACUERDO_LOTE',
                'ordering': ['fecha_vencimiento', 'batch_number'],
            },
        ),
        migrations.AddField(
            model_name='citacion_despacho_acuerdo_estanque',
            name='acuerdo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estanques', to='home.citacion_despacho_acuerdo_operacional'),
        ),
        migrations.CreateModel(
            name='CITACION_DESPACHO_CARGA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_total', models.DecimalField(decimal_places=5, max_digits=18)),
                ('zona_carga', models.CharField(max_length=64)),
                ('version', models.PositiveIntegerField(default=1)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('CI_NID', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='carga_despacho', to='home.citacion')),
                ('US_NID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'CITACION_DESPACHO_CARGA',
            },
        ),
        migrations.AddField(
            model_name='citacion_despacho_acuerdo_operacional',
            name='carga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acuerdos', to='home.citacion_despacho_carga'),
        ),
        migrations.CreateModel(
            name='CITACION_DESPACHO_DRAFT_SAP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_idempotencia', models.CharField(max_length=128, unique=True)),
                ('estado', models.CharField(choices=[('PREPARADO', 'Preparado'), ('ENVIANDO', 'Enviando'), ('CREADO', 'Creado'), ('ERROR', 'Error confirmado'), ('INCIERTO', 'Requiere conciliación')], default='PREPARADO', max_length=20)),
                ('docentry', models.CharField(blank=True, max_length=64)),
                ('docnum', models.CharField(blank=True, max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('respuesta', models.JSONField(default=dict)),
                ('error', models.TextField(blank=True)),
                ('intentos', models.PositiveIntegerField(default=0)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('acuerdo', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='draft', to='home.citacion_despacho_acuerdo_operacional')),
            ],
            options={
                'db_table': 'CITACION_DESPACHO_DRAFT_SAP',
            },
        ),
        migrations.AddConstraint(
            model_name='citacion_despacho_acuerdo_lote',
            constraint=models.UniqueConstraint(fields=('estanque', 'batch_number'), name='DESP_OP_LOTE_UNQ'),
        ),
        migrations.AddConstraint(
            model_name='citacion_despacho_acuerdo_lote',
            constraint=models.CheckConstraint(check=models.Q(('cantidad__gt', 0), ('cantidad__lte', models.F('stock_snapshot'))), name='DESP_OP_LOTE_STOCK'),
        ),
        migrations.AddConstraint(
            model_name='citacion_despacho_acuerdo_estanque',
            constraint=models.UniqueConstraint(fields=('acuerdo', 'warehouse_code', 'item_code'), name='DESP_OP_TK_ITEM_UNQ'),
        ),
        migrations.AddConstraint(
            model_name='citacion_despacho_acuerdo_estanque',
            constraint=models.CheckConstraint(check=models.Q(('cantidad__gt', 0)), name='DESP_OP_TK_POS'),
        ),
        migrations.AddConstraint(
            model_name='citacion_despacho_carga',
            constraint=models.CheckConstraint(check=models.Q(('cantidad_total__gt', 0)), name='DESP_CARGA_TOTAL_POS'),
        ),
        migrations.AddConstraint(
            model_name='citacion_despacho_acuerdo_operacional',
            constraint=models.UniqueConstraint(fields=('carga', 'sap_abs_id'), name='DESP_OP_ACUERDO_UNQ'),
        ),
        migrations.AddConstraint(
            model_name='citacion_despacho_acuerdo_operacional',
            constraint=models.CheckConstraint(check=models.Q(('cantidad__gt', 0)), name='DESP_OP_ACUERDO_POS'),
        ),
    ]
