# Generated by Django 5.0.2 on 2026-09-15 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0121_despacho_carga_operacional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camion_patio',
            name='CPA_CESTADO',
            field=models.CharField(choices=[('PENDIENTE_ASOCIACION', 'Pendiente asociacion'), ('EN_REVISION_RECEPCION', 'En revision recepcion'), ('ASOCIADO_CITACION', 'Asociado a citacion'), ('SALIDA_CONFIRMADA', 'Salida confirmada'), ('RECHAZADO', 'Rechazado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE_ASOCIACION', max_length=32, verbose_name='Estado'),
        ),
    ]
