# Generated by Django 5.0.2 on 2026-09-17 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

SECUENCIAS_PROSESA = (
    ('RECEPCION_PROSESA_PISO_1', 'Prosesa - Contenedor a Piso 1'),
    ('RECEPCION_PROSESA_PISO_2', 'Prosesa - Contenedor a Piso 2'),
)


def crear_secuencias_prosesa(apps, schema_editor):
    Secuencia = apps.get_model('home', 'SECUENCIA')
    DetalleSecuencia = apps.get_model('home', 'DETALLE_SECUENCIA')
    base = Secuencia.objects.filter(
        EP_NID_id=2,
        SE_CTIPO='RECEPCION',
        SE_CCODIGO='RECEPCION_BODEGA_EXTERNA',
    ).first()
    if not base:
        return

    detalles_base = list(
        DetalleSecuencia.objects.filter(
            SC_NID=base,
            SE_BHABILITADO=True,
        ).order_by('SE_NPASO', 'id')
    )
    for codigo, nombre in SECUENCIAS_PROSESA:
        secuencia, _ = Secuencia.objects.get_or_create(
            EP_NID_id=2,
            SE_CCODIGO=codigo,
            defaults={
                'US_NID_id': base.US_NID_id,
                'SE_CTIPO': 'RECEPCION',
                'SE_CNOMBRE': nombre,
                'SE_BHABILITADO': True,
            },
        )
        campos_actualizados = []
        for campo, valor in (
            ('SE_CTIPO', 'RECEPCION'),
            ('SE_CNOMBRE', nombre),
            ('SE_BHABILITADO', True),
        ):
            if getattr(secuencia, campo) != valor:
                setattr(secuencia, campo, valor)
                campos_actualizados.append(campo)
        if campos_actualizados:
            secuencia.save(update_fields=campos_actualizados)

        if not DetalleSecuencia.objects.filter(SC_NID=secuencia).exists():
            DetalleSecuencia.objects.bulk_create([
                DetalleSecuencia(
                    EP_NID_id=2,
                    SC_NID=secuencia,
                    ET_NID_id=detalle.ET_NID_id,
                    SE_NPASO=detalle.SE_NPASO,
                    SE_BHABILITADO=detalle.SE_BHABILITADO,
                    SE_BOBLIGATORIO=detalle.SE_BOBLIGATORIO,
                )
                for detalle in detalles_base
            ])



class Migration(migrations.Migration):

    dependencies = [
        ('home', '0123_camion_patio_conductor_maestro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CITACION_PROSESA_RELACION',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CPR_FFECHACREACION', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creacion')),
                ('CI_NID_ORIGEN', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='relacion_prosesa_origen', to='home.citacion', verbose_name='Citacion Prosesa Piso 1')),
                ('CI_NID_RETIRO', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='relacion_prosesa_retiro', to='home.citacion', verbose_name='Citacion Prosesa Piso 2')),
                ('EP_NID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.empresa', verbose_name='Id empresa')),
                ('US_NID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario creacion')),
            ],
            options={
                'db_table': 'CITACION_PROSESA_RELACION',
                'indexes': [models.Index(fields=['EP_NID', 'CPR_FFECHACREACION'], name='CIT_PROSESA_EP_FECHA_IDX')],
            },
        ),
        migrations.RunPython(crear_secuencias_prosesa, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='citacion_prosesa_relacion',
            constraint=models.CheckConstraint(check=models.Q(('CI_NID_ORIGEN', models.F('CI_NID_RETIRO')), _negated=True), name='CIT_PROSESA_ORIGEN_RETIRO_DISTINTOS'),
        ),
    ]
