# Generated by Django 5.0.2 on 2026-09-21 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0124_recepcion_prosesa_pisos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultado_calidad_historial',
            name='RCH_CORIGEN',
            field=models.CharField(choices=[('OPERACION_PLANTA', 'Operacion Planta'), ('EXCEL_CALIDAD', 'Excel Calidad'), ('CORREO_CLIENTE', 'Correo cliente'), ('REVISION_MANUAL', 'Revision manual'), ('MANUAL_PRUEBA', 'Manual / prueba')], max_length=32, verbose_name='Origen'),
        ),
        migrations.AlterField(
            model_name='resultado_calidad_operacion',
            name='RCO_CESTADO',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('RECHAZADO_PENDIENTE_REVISION', 'Rechazado - pendiente revision manual'), ('APRUEBA_CLIENTE', 'Aprueba cliente')], default='PENDIENTE', max_length=32, verbose_name='Estado actual'),
        ),
        migrations.AlterField(
            model_name='resultado_calidad_operacion',
            name='RCO_CORIGEN',
            field=models.CharField(choices=[('OPERACION_PLANTA', 'Operacion Planta'), ('EXCEL_CALIDAD', 'Excel Calidad'), ('CORREO_CLIENTE', 'Correo cliente'), ('REVISION_MANUAL', 'Revision manual'), ('MANUAL_PRUEBA', 'Manual / prueba')], default='OPERACION_PLANTA', max_length=32, verbose_name='Origen actualizacion'),
        ),
    ]
