# Generated by Django 5.0.2 on 2026-09-25 04:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0126_citacion_despacho_fecha_llegada_destino'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OPERACION_NEW_JERSEY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ONJ_CMODALIDAD', models.CharField(choices=[('CON_CALIDAD', 'Contenedor a Piso con Calidad'), ('SIN_CALIDAD', 'Contenedor a Piso sin Calidad')], max_length=32, verbose_name='Modalidad')),
                ('ONJ_CESTADO', models.CharField(choices=[('PENDIENTE_PROCESO_1', 'Pendiente Proceso 1'), ('CONTENEDOR_EN_NEW_JERSEY', 'Contenedor en New Jersey'), ('PENDIENTE_PROCESO_2', 'Pendiente Proceso 2'), ('TRASLADO_PREPARADO', 'Traslado preparado'), ('PENDIENTE_PROCESO_3', 'Pendiente Proceso 3'), ('PENDIENTE_PESO_FINAL', 'Pendiente peso final'), ('LISTA_TRANSFERENCIA_SAP', 'Lista transferencia SAP'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE_PROCESO_1', max_length=40, verbose_name='Estado')),
                ('ONJ_CITEM_CODE', models.CharField(blank=True, max_length=128, null=True, verbose_name='ItemCode')),
                ('ONJ_CPRODUCTO', models.CharField(blank=True, max_length=256, null=True, verbose_name='Producto')),
                ('ONJ_CPURCHASE_ORDER', models.CharField(blank=True, max_length=128, null=True, verbose_name='Purchase Order')),
                ('ONJ_CBASE_ENTRY', models.CharField(blank=True, max_length=128, null=True, verbose_name='BaseEntry')),
                ('ONJ_CBASE_LINE', models.CharField(blank=True, max_length=128, null=True, verbose_name='BaseLine')),
                ('ONJ_CBODEGA_VIRTUAL', models.CharField(max_length=128, verbose_name='Bodega virtual')),
                ('ONJ_CTK_DESTINO', models.CharField(blank=True, max_length=128, null=True, verbose_name='TK destino')),
                ('ONJ_FFECHA_OPERACION', models.DateTimeField(blank=True, null=True, verbose_name='Fecha operacion')),
                ('ONJ_FFECHACREACION', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creacion')),
                ('ONJ_FFECHAMODIFICACION', models.DateTimeField(auto_now=True, verbose_name='Fecha modificacion')),
                ('ONJ_BHABILITADO', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('EP_NID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.empresa', verbose_name='Id empresa')),
                ('PRO_NID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operaciones_new_jersey', to='home.socionegocio', verbose_name='Proveedor')),
                ('US_NID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario creacion')),
            ],
            options={
                'db_table': 'OPERACION_NEW_JERSEY',
            },
        ),
        migrations.CreateModel(
            name='OPERACION_NEW_JERSEY_PROCESO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ONJP_CTIPO', models.CharField(choices=[('PROCESO_1', 'Proceso 1'), ('PROCESO_2', 'Proceso 2'), ('PROCESO_3', 'Proceso 3')], max_length=20, verbose_name='Tipo proceso')),
                ('ONJP_CESTADO', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('ONJP_FFECHACREACION', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creacion')),
                ('ONJP_FFECHAMODIFICACION', models.DateTimeField(auto_now=True, verbose_name='Fecha modificacion')),
                ('CI_NID', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='proceso_new_jersey', to='home.citacion', verbose_name='Citacion')),
                ('EP_NID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.empresa', verbose_name='Id empresa')),
                ('ONJ_NID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procesos', to='home.operacion_new_jersey', verbose_name='Operacion New Jersey')),
                ('US_NID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario creacion')),
            ],
            options={
                'db_table': 'OPERACION_NEW_JERSEY_PROCESO',
            },
        ),
        migrations.AddIndex(
            model_name='operacion_new_jersey',
            index=models.Index(fields=['EP_NID', 'ONJ_CESTADO'], name='NJ_OPER_EP_EST_IDX'),
        ),
        migrations.AddIndex(
            model_name='operacion_new_jersey',
            index=models.Index(fields=['ONJ_CITEM_CODE'], name='NJ_OPER_ITEM_IDX'),
        ),
        migrations.AddIndex(
            model_name='operacion_new_jersey_proceso',
            index=models.Index(fields=['EP_NID', 'ONJP_CTIPO'], name='NJ_PROC_EP_TIPO_IDX'),
        ),
        migrations.AddConstraint(
            model_name='operacion_new_jersey_proceso',
            constraint=models.UniqueConstraint(fields=('ONJ_NID', 'ONJP_CTIPO'), name='NJ_PROC_OPER_TIPO_UNQ'),
        ),
    ]
