
#VARIABLES DE CONFIGURACION GLOBAL
DOCUMENTOS_CAMIONES_TERRAMAR_PATH = 'C:\\Documentos\\Terramar\\Camiones'
DOCUMENTOS_PROVEEDORES_TERRAMAR_PATH = 'C:\\Documentos\\Terramar\\Proveedores'
DOCUMENTOS_CLIENTES_TERRAMAR_PATH = 'C:\\Documentos\\Terramar\\Clientes'
DOCUMENTOS_CONDUCTORES_TERRAMAR_PATH = 'C:\\Documentos\\Terramar\\Conductores'
DOCUMENTOS_PROFORMA_TERRAMAR_PATH = 'C:\\Documentos\\Terramar\\Proforma'

DOCUMENTOS_CAMIONES_ACEITES_PATH = 'C:\\Documentos\\Aceites\\Camiones'
DOCUMENTOS_PROVEEDORES_ACEITES_PATH = 'C:\\Documentos\\Aceites\\Proveedores'
DOCUMENTOS_CLIENTES_ACEITES_PATH = 'C:\\Documentos\\Aceites\\Clientes'
DOCUMENTOS_CONDUCTORE_ACEITESS_PATH = 'C:\\Documentos\\Aceites\\Conductores'
DOCUMENTOS_PROFORMA_ACEITESS_PATH = 'C:\\Documentos\\Aceites\\Proforma'

CAMPO_TERRAMAR_PATH = 'C:\\Secuencia\\Terramar'
CAMPO_ACEITES_PATH = 'C:\\Secuencia\\Aceites'

ID_TERRAMAR = 1
ID_ACEITES_SBH = 2

URL_BASE_API = "https://9f96-181-43-212-235.ngrok-free.app/"

LAT_INIT = "-36.950493"
LON_INIT = "-73.157457"
MAP_ZOOM_INIT = 20
MAP_HEIGHT_RAM = '600px'

USER_DEFAULT_PASSWORD_CONDUCTOR = "pbkdf2_sha256$720000$6WySeVBJUScxoFB1d3CucD$xuY0JnlmQJB7Bsg7suW1Mov9OZRpsMTmtEnflVcu1UY="
USER_DEFAULT_PASSWORD_PROVEEDOR = "pbkdf2_sha256$720000$vGHrg0EzilS2id6RR3E8oJ$Lw26WYOnLsiY5hYHf98QUGJzwBaO9fdddlntHq3YYLQ="
USER_DEFAULT_PASSWORD_CLIENTE = "pbkdf2_sha256$720000$PrrbffVBkPi6MU9swFVHbi$6mOrh7n2fvMof3JxSKJcZqQDgC1Bn1Otcddl622pj4U="
USER_DEFAULT_PASSWORD_USER = "pbkdf2_sha256$720000$iRC2VM0I9dUAqjmXdcd5kt$dPRdMZTUBpjQ9KvRWxh1lYu2gLHm+iWvylZ/Xuq8p58="
# Usuario.2023

# ESTADOS CITACION
CIT_CREADO = 'CREADO'
CIT_EN_PROCESO = 'EN PROCESO'
CIT_TERMINADO = 'TERMINADO'
CIT_RECHAZADO = 'RECHAZADO'

# TIPOS CITACION
CIT_DESPACHO = 'DESPACHO'
CIT_RECEPCION = 'RECEPCION'
